/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CryptoIrcClient.GUI;

import CryptoIrcClient.MainThread;

/**
 *
 * @author Илья
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private int mXMouseDrag;
    private int mYMouseDrag;
    
    private Button exitButtonController;
    private Button minimizeButtonController;
    private ButtonA enterButtonController;
    /**
     * Creates new form MainFrame
     */
    public LoginFrame() {
        initComponents();
        exitButtonController = new Button(
                exitButton,
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/exitIdleButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/exitHoverButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/exitPressedButton.png"))
        );
        minimizeButtonController = new Button(
                minimizeButton,
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/minimizeIdleButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/minimizeHoverButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/minimizePressedButton.png"))
        );
        enterButtonController = new ButtonA(
                enterButton,
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/enterIdleButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/enterHoverButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/enterPressedButton.png")),
                new javax.swing.ImageIcon(getClass().getResource("/resources/icons/enterDisabledButton.png")),
                false
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        rememberUser = new javax.swing.JCheckBox();
        enterButton = new javax.swing.JLabel();
        loginFrameBottom = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        systemBar = new javax.swing.JLabel();
        loginFrameText = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/exitIdleButton.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 6, -1, -1));

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/minimizeIdleButton.png"))); // NOI18N
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 6, -1, -1));

        container.setOpaque(false);
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Имя пользователя:");
        container.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        loginTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        loginTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginTextFieldFocusLost(evt);
            }
        });
        loginTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginTextFieldKeyTyped(evt);
            }
        });
        container.add(loginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 240, -1));

        passwordLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Пароль:");
        container.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });
        container.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 240, -1));

        rememberUser.setBackground(new java.awt.Color(0, 0, 0));
        rememberUser.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        rememberUser.setForeground(new java.awt.Color(255, 255, 255));
        rememberUser.setText("Запомнить пользователя");
        rememberUser.setOpaque(false);
        container.add(rememberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/enterDisabledButton.png"))); // NOI18N
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enterButtonMouseReleased(evt);
            }
        });
        container.add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        loginFrameBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/graphics/LoginFrameBottom.png"))); // NOI18N
        container.add(loginFrameBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        systemBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/graphics/SystemBar.png"))); // NOI18N
        getContentPane().add(systemBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginFrameText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/graphics/LoginFrameText.png"))); // NOI18N
        getContentPane().add(loginFrameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/graphics/BackGround.png"))); // NOI18N
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mXMouseDrag, y - mYMouseDrag);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        mXMouseDrag = evt.getX();                                       
        mYMouseDrag = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        exitButtonController.press();
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
        if(exitButtonController.isPressed() && exitButtonController.isHovered()){
            System.exit(0);
        }
        exitButtonController.release();
    }//GEN-LAST:event_exitButtonMouseReleased

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButtonController.hover();
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButtonController.unHover();
    }//GEN-LAST:event_exitButtonMouseExited

    private void minimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseEntered
        minimizeButtonController.hover();
    }//GEN-LAST:event_minimizeButtonMouseEntered

    private void minimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseExited
        minimizeButtonController.unHover();
    }//GEN-LAST:event_minimizeButtonMouseExited

    private void minimizeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMousePressed
        minimizeButtonController.press();
    }//GEN-LAST:event_minimizeButtonMousePressed

    private void minimizeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseReleased
        if(minimizeButtonController.isPressed() && minimizeButtonController.isHovered()){
            this.setState(LoginFrame.ICONIFIED);
        }
        minimizeButtonController.release();
    }//GEN-LAST:event_minimizeButtonMouseReleased

    private void loginTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginTextFieldFocusLost
        tryEnableEnterButton();
    }//GEN-LAST:event_loginTextFieldFocusLost

    private void loginTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTextFieldKeyTyped
        tryEnableEnterButton();
    }//GEN-LAST:event_loginTextFieldKeyTyped

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        tryEnableEnterButton();
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        tryEnableEnterButton();
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void enterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseEntered
        enterButtonController.hover();
    }//GEN-LAST:event_enterButtonMouseEntered

    private void enterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseExited
        enterButtonController.unHover();
    }//GEN-LAST:event_enterButtonMouseExited

    private void enterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMousePressed
        enterButtonController.press();
    }//GEN-LAST:event_enterButtonMousePressed

    private void enterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseReleased
        if(enterButtonController.isPressed() && enterButtonController.isHovered()){
            //System.out.println("LOGIN    : " + loginTextField.getText());
            //System.out.println("PASSWORD : " + passwordField.getPassword());
            MainThread.Login(loginTextField.getText(), new String(passwordField.getPassword()));
        }
        enterButtonController.release();
    }//GEN-LAST:event_enterButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    
    private void tryEnableEnterButton(){
        if(passwordField.getPassword().length > 0 && loginTextField.getText().length() > 0){
            enterButtonController.enable();
        }else{
            enterButtonController.disable();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel backGround;
    private javax.swing.JPanel container;
    private javax.swing.JLabel enterButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel loginFrameBottom;
    private javax.swing.JLabel loginFrameText;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JCheckBox rememberUser;
    private javax.swing.JLabel systemBar;
    // End of variables declaration//GEN-END:variables
}